// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculatorpb/cal.proto

package calculatorpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddReauest struct {
	FirstNum             int32    `protobuf:"varint,1,opt,name=firstNum,proto3" json:"firstNum,omitempty"`
	SecondNum            int32    `protobuf:"varint,2,opt,name=secondNum,proto3" json:"secondNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddReauest) Reset()         { *m = AddReauest{} }
func (m *AddReauest) String() string { return proto.CompactTextString(m) }
func (*AddReauest) ProtoMessage()    {}
func (*AddReauest) Descriptor() ([]byte, []int) {
	return fileDescriptor_207bc08326e5753a, []int{0}
}

func (m *AddReauest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddReauest.Unmarshal(m, b)
}
func (m *AddReauest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddReauest.Marshal(b, m, deterministic)
}
func (m *AddReauest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddReauest.Merge(m, src)
}
func (m *AddReauest) XXX_Size() int {
	return xxx_messageInfo_AddReauest.Size(m)
}
func (m *AddReauest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddReauest.DiscardUnknown(m)
}

var xxx_messageInfo_AddReauest proto.InternalMessageInfo

func (m *AddReauest) GetFirstNum() int32 {
	if m != nil {
		return m.FirstNum
	}
	return 0
}

func (m *AddReauest) GetSecondNum() int32 {
	if m != nil {
		return m.SecondNum
	}
	return 0
}

type CalResult struct {
	Calresult            int32    `protobuf:"varint,1,opt,name=calresult,proto3" json:"calresult,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalResult) Reset()         { *m = CalResult{} }
func (m *CalResult) String() string { return proto.CompactTextString(m) }
func (*CalResult) ProtoMessage()    {}
func (*CalResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_207bc08326e5753a, []int{1}
}

func (m *CalResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalResult.Unmarshal(m, b)
}
func (m *CalResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalResult.Marshal(b, m, deterministic)
}
func (m *CalResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalResult.Merge(m, src)
}
func (m *CalResult) XXX_Size() int {
	return xxx_messageInfo_CalResult.Size(m)
}
func (m *CalResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CalResult.DiscardUnknown(m)
}

var xxx_messageInfo_CalResult proto.InternalMessageInfo

func (m *CalResult) GetCalresult() int32 {
	if m != nil {
		return m.Calresult
	}
	return 0
}

type AvgRequest struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvgRequest) Reset()         { *m = AvgRequest{} }
func (m *AvgRequest) String() string { return proto.CompactTextString(m) }
func (*AvgRequest) ProtoMessage()    {}
func (*AvgRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_207bc08326e5753a, []int{2}
}

func (m *AvgRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvgRequest.Unmarshal(m, b)
}
func (m *AvgRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvgRequest.Marshal(b, m, deterministic)
}
func (m *AvgRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvgRequest.Merge(m, src)
}
func (m *AvgRequest) XXX_Size() int {
	return xxx_messageInfo_AvgRequest.Size(m)
}
func (m *AvgRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AvgRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AvgRequest proto.InternalMessageInfo

func (m *AvgRequest) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type AvgResult struct {
	CalResule            float64  `protobuf:"fixed64,1,opt,name=calResule,proto3" json:"calResule,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvgResult) Reset()         { *m = AvgResult{} }
func (m *AvgResult) String() string { return proto.CompactTextString(m) }
func (*AvgResult) ProtoMessage()    {}
func (*AvgResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_207bc08326e5753a, []int{3}
}

func (m *AvgResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvgResult.Unmarshal(m, b)
}
func (m *AvgResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvgResult.Marshal(b, m, deterministic)
}
func (m *AvgResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvgResult.Merge(m, src)
}
func (m *AvgResult) XXX_Size() int {
	return xxx_messageInfo_AvgResult.Size(m)
}
func (m *AvgResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AvgResult.DiscardUnknown(m)
}

var xxx_messageInfo_AvgResult proto.InternalMessageInfo

func (m *AvgResult) GetCalResule() float64 {
	if m != nil {
		return m.CalResule
	}
	return 0
}

func init() {
	proto.RegisterType((*AddReauest)(nil), "gRPC_Calculator.addReauest")
	proto.RegisterType((*CalResult)(nil), "gRPC_Calculator.calResult")
	proto.RegisterType((*AvgRequest)(nil), "gRPC_Calculator.AvgRequest")
	proto.RegisterType((*AvgResult)(nil), "gRPC_Calculator.avgResult")
}

func init() { proto.RegisterFile("calculatorpb/cal.proto", fileDescriptor_207bc08326e5753a) }

var fileDescriptor_207bc08326e5753a = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcb, 0x4a, 0x03, 0x31,
	0x14, 0x86, 0x1b, 0x8b, 0xc5, 0x1e, 0x44, 0x21, 0x8b, 0x22, 0xa3, 0x0b, 0x09, 0x2e, 0xea, 0x66,
	0x04, 0x7d, 0x01, 0xa7, 0x2d, 0xba, 0x13, 0x89, 0xe0, 0xc2, 0x8d, 0x9c, 0x49, 0x8e, 0xa5, 0x90,
	0x76, 0x6a, 0x2e, 0x7d, 0x10, 0x9f, 0x58, 0x12, 0x86, 0xa4, 0x68, 0x97, 0xff, 0x85, 0x2f, 0x7f,
	0x38, 0x30, 0x51, 0x68, 0x54, 0x30, 0xe8, 0x3b, 0xbb, 0x6d, 0xef, 0x14, 0x9a, 0x7a, 0x6b, 0x3b,
	0xdf, 0xf1, 0xf3, 0xa5, 0x7c, 0x9d, 0x7f, 0xce, 0x73, 0x28, 0x9e, 0x00, 0x50, 0x6b, 0x49, 0x18,
	0xc8, 0x79, 0x5e, 0xc1, 0xc9, 0xd7, 0xca, 0x3a, 0xff, 0x12, 0xd6, 0x17, 0xec, 0x9a, 0x4d, 0x8f,
	0x65, 0xd6, 0xfc, 0x0a, 0xc6, 0x8e, 0x54, 0xb7, 0xd1, 0x31, 0x3c, 0x4a, 0x61, 0x31, 0xc4, 0x2d,
	0x8c, 0x15, 0x1a, 0x49, 0x2e, 0x18, 0x1f, 0xab, 0x0a, 0x8d, 0x4d, 0xa2, 0xe7, 0x14, 0x43, 0xdc,
	0x00, 0x34, 0xbb, 0xa5, 0xa4, 0xef, 0xf4, 0xe4, 0x04, 0x46, 0x9b, 0xb0, 0x6e, 0xc9, 0xf6, 0xc5,
	0x5e, 0x45, 0x20, 0xc6, 0xd6, 0x1e, 0x30, 0x09, 0x4a, 0x3d, 0x26, 0x8b, 0x71, 0xff, 0xc3, 0x00,
	0x1a, 0xad, 0xdf, 0xc8, 0xee, 0x56, 0x8a, 0xf8, 0x23, 0x0c, 0x9b, 0xc5, 0x82, 0x5f, 0xd6, 0x7f,
	0xfe, 0x5a, 0x97, 0x8f, 0x56, 0xd5, 0xbf, 0x30, 0xaf, 0x17, 0x03, 0x3e, 0x83, 0x61, 0xf3, 0xfe,
	0x7c, 0x80, 0x50, 0x76, 0x1f, 0x20, 0xe4, 0xb9, 0x62, 0x30, 0x65, 0xb3, 0xb3, 0x8f, 0xd3, 0xfd,
	0x1b, 0xb4, 0xa3, 0x74, 0x80, 0x87, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x28, 0x07, 0x45, 0xc5,
	0x9a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AddServiceClient is the client API for AddService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AddServiceClient interface {
	ADD(ctx context.Context, in *AddReauest, opts ...grpc.CallOption) (*CalResult, error)
	AVG(ctx context.Context, opts ...grpc.CallOption) (AddService_AVGClient, error)
}

type addServiceClient struct {
	cc *grpc.ClientConn
}

func NewAddServiceClient(cc *grpc.ClientConn) AddServiceClient {
	return &addServiceClient{cc}
}

func (c *addServiceClient) ADD(ctx context.Context, in *AddReauest, opts ...grpc.CallOption) (*CalResult, error) {
	out := new(CalResult)
	err := c.cc.Invoke(ctx, "/gRPC_Calculator.AddService/ADD", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *addServiceClient) AVG(ctx context.Context, opts ...grpc.CallOption) (AddService_AVGClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AddService_serviceDesc.Streams[0], "/gRPC_Calculator.AddService/AVG", opts...)
	if err != nil {
		return nil, err
	}
	x := &addServiceAVGClient{stream}
	return x, nil
}

type AddService_AVGClient interface {
	Send(*AvgRequest) error
	CloseAndRecv() (*AvgResult, error)
	grpc.ClientStream
}

type addServiceAVGClient struct {
	grpc.ClientStream
}

func (x *addServiceAVGClient) Send(m *AvgRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *addServiceAVGClient) CloseAndRecv() (*AvgResult, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(AvgResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AddServiceServer is the server API for AddService service.
type AddServiceServer interface {
	ADD(context.Context, *AddReauest) (*CalResult, error)
	AVG(AddService_AVGServer) error
}

func RegisterAddServiceServer(s *grpc.Server, srv AddServiceServer) {
	s.RegisterService(&_AddService_serviceDesc, srv)
}

func _AddService_ADD_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReauest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddServiceServer).ADD(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gRPC_Calculator.AddService/ADD",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddServiceServer).ADD(ctx, req.(*AddReauest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AddService_AVG_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AddServiceServer).AVG(&addServiceAVGServer{stream})
}

type AddService_AVGServer interface {
	SendAndClose(*AvgResult) error
	Recv() (*AvgRequest, error)
	grpc.ServerStream
}

type addServiceAVGServer struct {
	grpc.ServerStream
}

func (x *addServiceAVGServer) SendAndClose(m *AvgResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *addServiceAVGServer) Recv() (*AvgRequest, error) {
	m := new(AvgRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _AddService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gRPC_Calculator.AddService",
	HandlerType: (*AddServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ADD",
			Handler:    _AddService_ADD_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AVG",
			Handler:       _AddService_AVG_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "calculatorpb/cal.proto",
}
